require Pod::Executable.execute_command('node', ['-p',
 'require.resolve(
   "react-native/scripts/react_native_pods.rb",
   {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.0'
prepare_react_native_project!

target 'RNIntegrationApp' do
  config = use_native_modules!
  # Comment the next line if you don't want to use dynamic frameworks
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  post_install do |installer|
    react_native_post_install(installer)
  end

end
